### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by crozo5** [rednblkx/HAP-ESPHome#21]
**Describe the bug**
I'm getting some issues when I try to install the following code

```
esphome:
    name: esp32c3-homekey
    friendly_name: ESP32C3 HOMEKEY

esp32:
  board: esp32-c3-devkitm-1
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.2.1
    platform_version: 6.7.0
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_LWIP_MAX_SOCKETS: "16"
      CONFIG_MBEDTLS_HKDF_C: y

# Enable logging
logger:

external_components:
  source: github://rednblkx/HAP-ESPHome@main
  refresh: 0s

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.202
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP32-C3 Fallback Hotspot"
    password: "OuKytjuuDIMp5"

captive_portal:

spi:
  clk_pin: 4
  miso_pin: 5
  mosi_pin: 6

pn532_spi:
  id: nfc_spi_module
  cs_pin: 1
  update_interval: 100ms
  on_tag:
    then:
      lambda: |-
        ESP_LOGI("INFO", "My Tag ID is: %s", x.c_str());
        if(x == YOUR_TAG_ID) {
          if (id(cupboard_lock).state == LOCK_STATE_LOCKED) {
            id(cupboard_lock).unlock();
          } else {
            id(cupboard_lock).lock();
          }
        }

homekit_base:
  setup_code: '466-37-726'

homekit:
  lock:
    - id: cupboard_lock
      nfc_id: nfc_spi_module
      on_hk_success:
        lambda: |-
          ESP_LOGI("INFO", "IssuerID: %s", x.c_str());
          ESP_LOGI("INFO", "EndpointID: %s", y.c_str());
          if (id(cupboard_lock).state == LOCK_STATE_LOCKED) {
            id(cupboard_lock).unlock();
          } else {
            id(cupboard_lock).lock();
          }
      on_hk_fail:
        lambda: |-
          ESP_LOGI("ERROR", "Authorizing HomeKit lock failed");
      hk_hw_finish: "SILVER"

button:
- platform: homekit_base
  factory_reset:
    name: "Reset Homekit pairings"

lock:
  - platform: template
    id: cupboard_lock
    name: "HomeKit Cupboard Lock"
    optimistic: True
    on_lock:
    - logger.log: "Door Locked!"
    - switch.turn_off: electronic_lock
    on_unlock:
    - logger.log: "Door Unlocked!"
    - switch.turn_on: electronic_lock
    - delay:  100ms
    - switch.turn_off: electronic_lock

output:
  - platform: gpio
    pin: 10
    id: 'lock_out'
switch:
  - platform: output
    id: electronic_lock
    output: 'lock_out'
```

Here's my output:
```
INFO ESPHome 2024.11.0
INFO Reading configuration /config/esphome/esp32c3-homekey.yaml...
INFO Updating https://github.com/rednblkx/HAP-ESPHome.git@main
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
INFO Generating C++ source...
INFO Updating https://github.com/espressif/esp-protocols.git@mdns-v1.3.2
INFO Updating https://github.com/espressif/idf-extra-components.git@master
INFO Updating submodules (libsodium/libsodium) for https://github.com/espressif/idf-extra-components.git@master
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/esphome/esphome/__main__.py", line 1036, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1023, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 452, in command_compile
    exit_code = write_cpp(config)
                ^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 213, in write_cpp
    return write_cpp_file()
           ^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 231, in write_cpp_file
    writer.write_cpp(code_s)
  File "/esphome/esphome/writer.py", line 341, in write_cpp
    copy_src_tree()
  File "/esphome/esphome/writer.py", line 307, in copy_src_tree
    copy_files()
  File "/esphome/esphome/components/esp32/__init__.py", line 743, in copy_files
    shutil.copytree(
  File "/usr/lib/python3.11/shutil.py", line 561, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/shutil.py", line 515, in _copytree
    raise Error(errors)
shutil.Error: [('/data/idf_components/dce99966/libsodium/LICENSE', '/data/build/esp32c3-homekey/components/libsodium/LICENSE', "[Errno 17] File exists: 'libsodium/LICENSE' -> '/data/build/esp32c3-homekey/components/libsodium/LICENSE'")]
```

**Comment by rednblkx** [comment]
Hi!

Sorry for the late reply.

Are you by any chance using the HASS ESPHome addon? remember someone had the same issue(can't find it now) while using the hass addon, it's some annoying thing it's doing.

Can confirm the attached configuration compiles just fine, suggest to try to do a clean build, there should be a "Clean Build Files" option on esphome dashboard
